language: ruby
rvm: 2.0.0-p247
before_script:
  - cp config/database.travis.yml config.database.yml
  - mysql -e 'create database asc_476_test;'
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
install:
  - bundle install --without-development
script: bundle exec rake test_with_coveralls
secure: "MFs59A6NhOymJD0eL+cAjiJDoTpeqZxR3fGcU35yxekw5KP/Z//qIKAZGK4itUyzHDo2JsfT1Ku4j/cNLyNpKAQdxhAs9JSQzyjczkqWBEC2vLMKey2PbA+Kr20ExrpE7hMgx9HyInwuOub3cBbw9N1BN0HwDl9Vr4b838Vzpxk="

